---
  parser:
    babel-eslint
  env:
    browser: true
    es6: true
    node: true
  extends:
    - airbnb
    - plugin:react/recommended
    - prettier
    - prettier/react
    - prettier/standard
  plugins:
    - react
    - prettier
    - standard
  rules:
    no-unused-vars: 0
    no-undef: 0
